module.exports = {
  ztb: {
    replacementText1: '准题宝',
    replacementText2: 'wx725144750f85c0b6',
    replacementText3: 'ZHUNTIBAO',
    script: 'yarn run build:mp-weixin:ztb',
    upload: 'yarn run upload:mp-weixin:ztb',
  },
  h5: {
    replacementText1: '',
    script: 'yarn run build:h5',
  },
  ykmf: {
    replacementText1: '医考魔方',
    replacementText2: 'wxe0763099749bcaf0',
    replacementText3: 'YIKAO',
    script: 'yarn run build:mp-weixin:ykmf',
    upload: 'yarn run upload:mp-weixin:ykmf',
  },
  zdytk: {
    replacementText1: '中大优题库',
    replacementText2: 'wxc45bdadb49998e61',
    replacementText3: 'YOUTIKU',
    script: 'yarn run build:mp-weixin:zdytk',
    upload: 'yarn run upload:mp-weixin:zdytk',
  },
  zdycschool: {
    replacementText1: '中大英才学校',
    replacementText2: 'wxd9d5bf1c8a87f4cd',
    replacementText3: 'ZHIBOYINGXIAO',
    script: 'yarn run build:mp-weixin:zdycschool',
    upload: 'yarn run upload:mp-weixin:zdycschool',
  },
  qysg: {
    replacementText1: '社赋社会工作平台',
    replacementText2: 'wxc9e85aef03e51db7',
    replacementText3: 'QINGYI',
    script: 'yarn run build:mp-weixin:qysg',
    upload: 'yarn run upload:mp-weixin:qysg',
  },
  xjsg: {
    replacementText1: '新疆社工',
    replacementText2: 'wx21b4505b127ad2bc',
    replacementText3: 'XINGJIANG',
    script: 'yarn run build:mp-weixin:xjsg',
    upload: 'yarn run upload:mp-weixin:xjsg',
  },
  yxb: {
    replacementText1: '医学宝',
    replacementText2: 'wxb4bf18afd2eb9989',
    replacementText3: 'YIXUEBAO',
    script: 'yarn run build:mp-weixin:yxb',
    upload: 'yarn run upload:mp-weixin:yxb',
  },
  sxsg: {
    replacementText1: '山西铸仁社工课堂',
    replacementText2: 'wx31fd09fe6223374e',
    replacementText3: 'SXSG',
    script: 'yarn run build:mp-weixin:sxsg',
    upload: 'yarn run upload:mp-weixin:sxsg',
  },
  sxsg: {
    replacementText1: '山西铸仁社工课堂',
    replacementText2: 'wx31fd09fe6223374e',
    replacementText3: 'SXSG',
    script: 'yarn run build:mp-weixin:sxsg',
    upload: 'yarn run upload:mp-weixin:sxsg',
  },
  xhsg: {
    replacementText1: '星河青少年社工',
    replacementText2: 'wxf9d0ce35ff2a32b8',
    replacementText3: 'XHSG',
    script: 'yarn run build:mp-weixin:xhsg',
    upload: 'yarn run upload:mp-weixin:xhsg',
  },
};
